services:
  # app starting from Dockerfile in current folder
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    command: npm run dev